name: 'Is Team Member'
description: 'Checks if someone is a member of a team in smile-io.'
author: 'SRE Guild'
inputs:
  organization:
    description: 'The organization name.'
    required: true
    default: 'smile-io'
  username:
    description: 'The username you want to check belongs to the team.'
    required: true
  token:
    description: 'GitHub access token.'
    required: true
  team_slug:
    description: 'The team slug you want to check the username.'
    required: true
  pull_request_number:
    description: 'Pull request number.'
    required: true
  repository:
    description: 'Pull request repository.'
    required: true
outputs:
  result:
    description: 'The result in either true or false'
runs:
  using: 'node16'
  main: 'src/main.js'
branding:
  icon: 'user-check'
  color: 'gray-dark'